### ISSUE TITLE
Can I use the script if our server is hosted by powerschool?

### ISSUE THREAD

**Issue by yizhangsouthlake** [Philip-Greyson/D118-PS-Student-Email#1]
How can I get the API client id and client secret? Our server is hosted by Powerschool.
Do I need to install any new plugin on the powerschool side to use this script?

Thanks,
Yi

**Comment by Philip-Greyson** [comment]
I am not sure if you can access the SQL database when it is hosted by PowerSchool, which this script tries to do. If you have something like https://dbeaver.io/ you can try connecting to the database and see if it is even possible.
If you cannot access the database, it should be possible to do everything with API calls only, it just may take more time to parse everything out which is why I went with the database access method which I am more familiar with.

To get the API Client ID and Secret, you need to create your own unique plugin that has at least the <oauth> tag in the plugin.xml. We already had this installed on our server, so I do not have hands on experience creating it but there is documentation on the PowerSchool developer site and you can find many posts in the community about making your own plugin to use the API: https://support.powerschool.com/developer/#/page/plugin-xml

Once the custom plugin is installed, you go to the Plugin Management Console (District > Page and Data Management > Plugin Management Configuration), click on the plugins name, then click on Data Provider Configuration to see the Client ID and Client Secret.

**Comment by yizhangsouthlake** [comment]
Thank you very much for the reply. I have SQL read only access and I can access it under a vpn connection provided by PowerSchool. This is very promising! Thanks again! Yi On Sep 8, 2023, at 9:30 AM, Philip Greyson ***@***.***> wrote:﻿
Closed #1 as completed.
